//! A small DuckDB application demonstrating compile-time capability gating.
//!
//! This example shows how capsec prevents unauthorized database operations
//! at compile time — not at runtime. If you uncomment the "COMPILE ERROR"
//! lines, the program won't build.
//!
//! Run with:
//!   cargo run -p capsec-example-db --example duck_db_app

use capsec::Has;
use capsec_example_db::{CapDb, DbAll, DbRead, DbWrite};

/// Analytics module: read-only access to the database.
///
/// This function only accepts `DbRead` capability. It literally cannot
/// execute INSERT/UPDATE/DELETE — the compiler rejects it.
fn run_analytics(db: &CapDb, cap: &impl Has<DbRead>) {
    println!("\n--- Analytics (read-only) ---");

    let rows = db.query(
        "SELECT CAST(id AS VARCHAR), name, CAST(score AS VARCHAR) FROM players ORDER BY score DESC",
        cap,
    ).unwrap();

    println!("{:<5} {:<15} {:<6}", "ID", "Name", "Score");
    println!("{:-<5} {:-<15} {:-<6}", "", "", "");
    for row in &rows {
        println!("{:<5} {:<15} {:<6}", row[0], row[1], row[2]);
    }

    let top = db
        .query_one("SELECT name FROM players ORDER BY score DESC LIMIT 1", cap)
        .unwrap();
    println!("\nTop player: {top}");

    let avg = db
        .query_one(
            "SELECT CAST(ROUND(AVG(score), 1) AS VARCHAR) FROM players",
            cap,
        )
        .unwrap();
    println!("Average score: {avg}");

    // COMPILE ERROR: uncomment to see capsec in action
    // db.execute("DELETE FROM players", cap);
    //                                   ^^^ the trait `Has<DbWrite>` is not
    //                                       implemented for `impl Has<DbRead>`
}

/// Ingestion module: write-only access to the database.
///
/// This function only accepts `DbWrite` capability. It can insert data
/// but cannot query it back.
fn ingest_scores(db: &CapDb, cap: &impl Has<DbWrite>) {
    println!("\n--- Ingestion (write-only) ---");

    let players = [
        ("Alice", 950),
        ("Bob", 870),
        ("Charlie", 1020),
        ("Diana", 890),
        ("Eve", 1100),
    ];

    for (name, score) in &players {
        db.execute(
            &format!("INSERT INTO players (name, score) VALUES ('{name}', {score})"),
            cap,
        )
        .unwrap();
        println!("  inserted: {name} (score: {score})");
    }

    // COMPILE ERROR: uncomment to see capsec in action
    // db.query("SELECT * FROM players", cap);
    //                                   ^^^ the trait `Has<DbRead>` is not
    //                                       implemented for `impl Has<DbWrite>`
}

/// Admin module: full access (read + write via DbAll).
///
/// `DbAll` subsumes both `DbRead` and `DbWrite`, so this function can
/// do everything — but it must be explicitly granted `DbAll`.
///
/// Note the pattern: we extract `Cap<DbAll>` from the capability holder,
/// then use it for both reads and writes. `Cap<DbAll>` implements both
/// `Has<DbRead>` and `Has<DbWrite>` via subsumption.
fn admin_cleanup(db: &CapDb, cap: &impl Has<DbAll>) {
    println!("\n--- Admin (full access) ---");

    // Extract a Cap<DbAll> — this concrete token satisfies Has<DbRead>
    // and Has<DbWrite> via the subsumption impls generated by
    // #[capsec::permission(subsumes = [DbRead, DbWrite])].
    let all_cap: capsec::Cap<DbAll> = cap.cap_ref();

    // Cap<DbAll> satisfies Has<DbRead> — can query
    let count = db
        .query_one(
            "SELECT CAST(COUNT(*) AS VARCHAR) FROM players WHERE score < 900",
            &all_cap,
        )
        .unwrap();
    println!("Players below 900: {count}");

    // Cap<DbAll> satisfies Has<DbWrite> — can delete
    let removed = db
        .execute("DELETE FROM players WHERE score < 900", &all_cap)
        .unwrap();
    println!("Removed {removed} player(s) below threshold");

    // Verify
    let remaining = db
        .query_one("SELECT CAST(COUNT(*) AS VARCHAR) FROM players", &all_cap)
        .unwrap();
    println!("Remaining players: {remaining}");
}

#[capsec::main]
fn main(root: capsec::CapRoot) {
    println!("=== DuckDB + capsec: Compile-Time Capability Gating ===");

    // Open an in-memory database
    let db = CapDb::open_in_memory().unwrap();

    // Grant DbAll for setup (migration needs read + write)
    let db_all = root.grant::<DbAll>();
    db.migrate(
        "CREATE SEQUENCE players_seq START 1;
        CREATE TABLE players (
            id INTEGER DEFAULT nextval('players_seq'),
            name VARCHAR NOT NULL,
            score INTEGER NOT NULL
        );",
        &db_all,
    )
    .unwrap();
    println!("Schema created.");

    // Grant narrow capabilities to each module.
    // Each module can ONLY do what its capability allows.
    let read_cap = root.grant::<DbRead>();
    let write_cap = root.grant::<DbWrite>();

    // Ingest: can write but not read
    ingest_scores(&db, &write_cap);

    // Analytics: can read but not write
    run_analytics(&db, &read_cap);

    // Admin: can do both (DbAll subsumes DbRead + DbWrite)
    admin_cleanup(&db, &db_all);

    // Final leaderboard
    println!("\n--- Final Leaderboard ---");
    let rows = db.query(
        "SELECT CAST(id AS VARCHAR), name, CAST(score AS VARCHAR) FROM players ORDER BY score DESC",
        &read_cap,
    ).unwrap();
    for row in &rows {
        println!("  #{}: {} ({})", row[0], row[1], row[2]);
    }

    println!("\nAll operations completed with compile-time capability enforcement.");
    println!("No runtime permission checks. Zero overhead. Just types.");
}
