#!/usr/bin/env python3
"""
Generate proofs/Capsec/Perm.lean from proofs/perms.toml.

Generates:
  - Perm inductive type with camelCase constructors
  - Subsumes inductive relation with refl + specific constructors
  - DecidableRel Subsumes instance
  - Perm.all list and Perm.mem_all theorem

Usage:
    python3 proofs/scripts/gen_perm.py
"""

import sys
from pathlib import Path

try:
    import tomllib
except ImportError:
    try:
        import tomli as tomllib
    except ImportError:
        print("Error: requires Python 3.11+ (tomllib) or tomli package", file=sys.stderr)
        sys.exit(1)

SCRIPT_DIR = Path(__file__).resolve().parent
PROOFS_DIR = SCRIPT_DIR.parent
TOML_PATH = PROOFS_DIR / "perms.toml"
OUTPUT_PATH = PROOFS_DIR / "Capsec" / "Perm.lean"


def to_camel(name: str) -> str:
    """PascalCase -> camelCase: FsRead -> fsRead, NetAll -> netAll."""
    if len(name) <= 1:
        return name.lower()
    # Find the boundary: lowercase starts after the uppercase prefix
    for i in range(1, len(name)):
        if name[i].islower():
            return name[:i].lower() + name[i:]
    return name.lower()


def generate(perms: list[str], subsumes: dict[str, list[str]]) -> str:
    lines = []
    lines.append("-- AUTO-GENERATED by proofs/scripts/gen_perm.py from proofs/perms.toml")
    lines.append("-- DO NOT EDIT MANUALLY — regenerate with: python3 proofs/scripts/gen_perm.py")
    lines.append("")

    # Perm inductive
    lines.append("inductive Perm where")
    for p in perms:
        lines.append(f"  | {to_camel(p)} : Perm")
    lines.append("  deriving DecidableEq, Repr, Inhabited")
    lines.append("")

    # Subsumes inductive
    lines.append("inductive Subsumes : Perm → Perm → Prop where")
    lines.append("  | refl (p : Perm) : Subsumes p p")
    for super_perm, sub_list in subsumes.items():
        for sub in sub_list:
            constructor_name = f"{to_camel(super_perm)}_{to_camel(sub)}"
            lines.append(
                f"  | {constructor_name} : Subsumes Perm.{to_camel(super_perm)} Perm.{to_camel(sub)}"
            )
    lines.append("")

    # DecidableRel instance
    lines.append("instance : DecidableRel Subsumes := fun a b =>")
    lines.append("  match a, b with")
    # Reflexive cases
    for p in perms:
        cc = to_camel(p)
        lines.append(f"  | .{cc}, .{cc} => isTrue (Subsumes.refl _)")
    # Subsumption cases
    for super_perm, sub_list in subsumes.items():
        for sub in sub_list:
            sc = to_camel(super_perm)
            subc = to_camel(sub)
            if sc != subc:  # skip reflexive (already handled)
                constructor_name = f"{sc}_{subc}"
                lines.append(f"  | .{sc}, .{subc} => isTrue Subsumes.{constructor_name}")
    # Default false case — all remaining (a, b) pairs where Subsumes a b is impossible.
    # We enumerate them explicitly so Lean can verify each is impossible.
    all_true_pairs = set()
    for p in perms:
        all_true_pairs.add((to_camel(p), to_camel(p)))  # reflexive
    for super_perm, sub_list in subsumes.items():
        for sub in sub_list:
            all_true_pairs.add((to_camel(super_perm), to_camel(sub)))

    for a in perms:
        for b in perms:
            ac, bc = to_camel(a), to_camel(b)
            if (ac, bc) not in all_true_pairs:
                lines.append(f"  | .{ac}, .{bc} => isFalse (by intro h; cases h)")
    lines.append("")

    # Perm.all list
    lines.append("def Perm.all : List Perm :=")
    items = ", ".join(f".{to_camel(p)}" for p in perms)
    lines.append(f"  [{items}]")
    lines.append("")

    # Perm.all_length theorem
    lines.append(f"theorem Perm.all_length : Perm.all.length = {len(perms)} := by native_decide")
    lines.append("")

    # Perm.mem_all theorem
    lines.append("theorem Perm.mem_all (p : Perm) : p ∈ Perm.all := by")
    lines.append("  cases p <;> simp [Perm.all]")
    lines.append("")

    return "\n".join(lines)


def main():
    with open(TOML_PATH, "rb") as f:
        data = tomllib.load(f)

    perms = data["permissions"]["variants"]
    subsumes = data["subsumes"]

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    content = generate(perms, subsumes)
    OUTPUT_PATH.write_text(content)
    print(f"Generated {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
