-- AUTO-GENERATED by proofs/scripts/gen_perm.py from proofs/perms.toml
-- DO NOT EDIT MANUALLY — regenerate with: python3 proofs/scripts/gen_perm.py

inductive Perm where
  | fsRead : Perm
  | fsWrite : Perm
  | fsAll : Perm
  | netConnect : Perm
  | netBind : Perm
  | netAll : Perm
  | envRead : Perm
  | envWrite : Perm
  | spawn : Perm
  | ambient : Perm
  deriving DecidableEq, Repr, Inhabited

inductive Subsumes : Perm → Perm → Prop where
  | refl (p : Perm) : Subsumes p p
  | fsAll_fsRead : Subsumes Perm.fsAll Perm.fsRead
  | fsAll_fsWrite : Subsumes Perm.fsAll Perm.fsWrite
  | netAll_netConnect : Subsumes Perm.netAll Perm.netConnect
  | netAll_netBind : Subsumes Perm.netAll Perm.netBind
  | ambient_fsRead : Subsumes Perm.ambient Perm.fsRead
  | ambient_fsWrite : Subsumes Perm.ambient Perm.fsWrite
  | ambient_fsAll : Subsumes Perm.ambient Perm.fsAll
  | ambient_netConnect : Subsumes Perm.ambient Perm.netConnect
  | ambient_netBind : Subsumes Perm.ambient Perm.netBind
  | ambient_netAll : Subsumes Perm.ambient Perm.netAll
  | ambient_envRead : Subsumes Perm.ambient Perm.envRead
  | ambient_envWrite : Subsumes Perm.ambient Perm.envWrite
  | ambient_spawn : Subsumes Perm.ambient Perm.spawn

instance : DecidableRel Subsumes := fun a b =>
  match a, b with
  | .fsRead, .fsRead => isTrue (Subsumes.refl _)
  | .fsWrite, .fsWrite => isTrue (Subsumes.refl _)
  | .fsAll, .fsAll => isTrue (Subsumes.refl _)
  | .netConnect, .netConnect => isTrue (Subsumes.refl _)
  | .netBind, .netBind => isTrue (Subsumes.refl _)
  | .netAll, .netAll => isTrue (Subsumes.refl _)
  | .envRead, .envRead => isTrue (Subsumes.refl _)
  | .envWrite, .envWrite => isTrue (Subsumes.refl _)
  | .spawn, .spawn => isTrue (Subsumes.refl _)
  | .ambient, .ambient => isTrue (Subsumes.refl _)
  | .fsAll, .fsRead => isTrue Subsumes.fsAll_fsRead
  | .fsAll, .fsWrite => isTrue Subsumes.fsAll_fsWrite
  | .netAll, .netConnect => isTrue Subsumes.netAll_netConnect
  | .netAll, .netBind => isTrue Subsumes.netAll_netBind
  | .ambient, .fsRead => isTrue Subsumes.ambient_fsRead
  | .ambient, .fsWrite => isTrue Subsumes.ambient_fsWrite
  | .ambient, .fsAll => isTrue Subsumes.ambient_fsAll
  | .ambient, .netConnect => isTrue Subsumes.ambient_netConnect
  | .ambient, .netBind => isTrue Subsumes.ambient_netBind
  | .ambient, .netAll => isTrue Subsumes.ambient_netAll
  | .ambient, .envRead => isTrue Subsumes.ambient_envRead
  | .ambient, .envWrite => isTrue Subsumes.ambient_envWrite
  | .ambient, .spawn => isTrue Subsumes.ambient_spawn
  | .fsRead, .fsWrite => isFalse (by intro h; cases h)
  | .fsRead, .fsAll => isFalse (by intro h; cases h)
  | .fsRead, .netConnect => isFalse (by intro h; cases h)
  | .fsRead, .netBind => isFalse (by intro h; cases h)
  | .fsRead, .netAll => isFalse (by intro h; cases h)
  | .fsRead, .envRead => isFalse (by intro h; cases h)
  | .fsRead, .envWrite => isFalse (by intro h; cases h)
  | .fsRead, .spawn => isFalse (by intro h; cases h)
  | .fsRead, .ambient => isFalse (by intro h; cases h)
  | .fsWrite, .fsRead => isFalse (by intro h; cases h)
  | .fsWrite, .fsAll => isFalse (by intro h; cases h)
  | .fsWrite, .netConnect => isFalse (by intro h; cases h)
  | .fsWrite, .netBind => isFalse (by intro h; cases h)
  | .fsWrite, .netAll => isFalse (by intro h; cases h)
  | .fsWrite, .envRead => isFalse (by intro h; cases h)
  | .fsWrite, .envWrite => isFalse (by intro h; cases h)
  | .fsWrite, .spawn => isFalse (by intro h; cases h)
  | .fsWrite, .ambient => isFalse (by intro h; cases h)
  | .fsAll, .netConnect => isFalse (by intro h; cases h)
  | .fsAll, .netBind => isFalse (by intro h; cases h)
  | .fsAll, .netAll => isFalse (by intro h; cases h)
  | .fsAll, .envRead => isFalse (by intro h; cases h)
  | .fsAll, .envWrite => isFalse (by intro h; cases h)
  | .fsAll, .spawn => isFalse (by intro h; cases h)
  | .fsAll, .ambient => isFalse (by intro h; cases h)
  | .netConnect, .fsRead => isFalse (by intro h; cases h)
  | .netConnect, .fsWrite => isFalse (by intro h; cases h)
  | .netConnect, .fsAll => isFalse (by intro h; cases h)
  | .netConnect, .netBind => isFalse (by intro h; cases h)
  | .netConnect, .netAll => isFalse (by intro h; cases h)
  | .netConnect, .envRead => isFalse (by intro h; cases h)
  | .netConnect, .envWrite => isFalse (by intro h; cases h)
  | .netConnect, .spawn => isFalse (by intro h; cases h)
  | .netConnect, .ambient => isFalse (by intro h; cases h)
  | .netBind, .fsRead => isFalse (by intro h; cases h)
  | .netBind, .fsWrite => isFalse (by intro h; cases h)
  | .netBind, .fsAll => isFalse (by intro h; cases h)
  | .netBind, .netConnect => isFalse (by intro h; cases h)
  | .netBind, .netAll => isFalse (by intro h; cases h)
  | .netBind, .envRead => isFalse (by intro h; cases h)
  | .netBind, .envWrite => isFalse (by intro h; cases h)
  | .netBind, .spawn => isFalse (by intro h; cases h)
  | .netBind, .ambient => isFalse (by intro h; cases h)
  | .netAll, .fsRead => isFalse (by intro h; cases h)
  | .netAll, .fsWrite => isFalse (by intro h; cases h)
  | .netAll, .fsAll => isFalse (by intro h; cases h)
  | .netAll, .envRead => isFalse (by intro h; cases h)
  | .netAll, .envWrite => isFalse (by intro h; cases h)
  | .netAll, .spawn => isFalse (by intro h; cases h)
  | .netAll, .ambient => isFalse (by intro h; cases h)
  | .envRead, .fsRead => isFalse (by intro h; cases h)
  | .envRead, .fsWrite => isFalse (by intro h; cases h)
  | .envRead, .fsAll => isFalse (by intro h; cases h)
  | .envRead, .netConnect => isFalse (by intro h; cases h)
  | .envRead, .netBind => isFalse (by intro h; cases h)
  | .envRead, .netAll => isFalse (by intro h; cases h)
  | .envRead, .envWrite => isFalse (by intro h; cases h)
  | .envRead, .spawn => isFalse (by intro h; cases h)
  | .envRead, .ambient => isFalse (by intro h; cases h)
  | .envWrite, .fsRead => isFalse (by intro h; cases h)
  | .envWrite, .fsWrite => isFalse (by intro h; cases h)
  | .envWrite, .fsAll => isFalse (by intro h; cases h)
  | .envWrite, .netConnect => isFalse (by intro h; cases h)
  | .envWrite, .netBind => isFalse (by intro h; cases h)
  | .envWrite, .netAll => isFalse (by intro h; cases h)
  | .envWrite, .envRead => isFalse (by intro h; cases h)
  | .envWrite, .spawn => isFalse (by intro h; cases h)
  | .envWrite, .ambient => isFalse (by intro h; cases h)
  | .spawn, .fsRead => isFalse (by intro h; cases h)
  | .spawn, .fsWrite => isFalse (by intro h; cases h)
  | .spawn, .fsAll => isFalse (by intro h; cases h)
  | .spawn, .netConnect => isFalse (by intro h; cases h)
  | .spawn, .netBind => isFalse (by intro h; cases h)
  | .spawn, .netAll => isFalse (by intro h; cases h)
  | .spawn, .envRead => isFalse (by intro h; cases h)
  | .spawn, .envWrite => isFalse (by intro h; cases h)
  | .spawn, .ambient => isFalse (by intro h; cases h)

def Perm.all : List Perm :=
  [.fsRead, .fsWrite, .fsAll, .netConnect, .netBind, .netAll, .envRead, .envWrite, .spawn, .ambient]

theorem Perm.all_length : Perm.all.length = 10 := by native_decide

theorem Perm.mem_all (p : Perm) : p ∈ Perm.all := by
  cases p <;> simp [Perm.all]
